name: publish
on:
  push:
    branches:
    - main
    tags:
    - '*'
jobs:
  publish-new-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pod repo push git@github.com:DoubleSymmetry/PrivatePodSpecs.git DSKit.podspec
