name: publish
on:
  push:
    branches:
    - master
    tags:
    - '*'
jobs:
  publish-new-version:
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Bundle Update
        run: gem install bundler:2.2.8
      - name: Bundle Install
        run: bundle install
      - name: Add Specs Repo
        run: pod repo add doublesymmetry https://${POD_GITHUB_API_TOKEN}@github.com/DoubleSymmetry/PrivatePodSpecs.git
        env:
          POD_GITHUB_API_TOKEN: ${{ secrets.CI_ACCESS }}
      - name: Publish New Version
        run: bundle exec pod repo push https://${POD_GITHUB_API_TOKEN}@github.com/DoubleSymmetry/PrivatePodSpecs.git DSKit.podspec
