name: publish
on:
  push:
    branches:
    - master
    tags:
    - '*'
jobs:
  publish-new-version:
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Cocoapods
        uses: maxim-lobanov/setup-cocoapods@v1
        with:
          version: 1.10.0
      - name: Add Specs Repo
        run: pod repo add doublesymmetry https://${POD_GITHUB_API_TOKEN}@github.com/DoubleSymmetry/PrivatePodSpecs.git
        env:
          POD_GITHUB_API_TOKEN: ${{ secrets.CI_ACCESS }}
      - name: Publish Pod
        run: bundle exec pod repo push https://${POD_GITHUB_API_TOKEN}@github.com/DoubleSymmetry/PrivatePodSpecs.git DSKit.podspec
