name: publish
on:
  push:
    branches:
    - master
    tags:
    - '*'
jobs:
  publish-new-version:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: maxim-lobanov/setup-cocoapods@v1
        with:
          version: 1.10.0
      - run: pod repo push git@github.com:DoubleSymmetry/PrivatePodSpecs.git DSKit.podspec
