name: publish
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]
jobs:
  run-tests:
    name: Test
    runs-on: blaze/macos-14
    strategy:
      matrix:
        xcode: [14.3.1, 15.0.1]
        destination: ["platform=iOS Simulator,name=iPhone 14 Pro"]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Xcode
        run: sudo xcode-select -s "/Applications/Xcode_${xcode}.app/Contents/Developer"
        env:
          xcode: ${{ matrix.xcode }}
      - name: Run Tests
        run: xcodebuild test -scheme DSKit -destination "${destination}"
        env:
          destination: ${{ matrix.destination }}
